# Generated by Django 4.0.3 on 2023-05-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_sales_code', models.CharField(max_length=20, verbose_name='售后编号')),
                ('sales_code', models.CharField(max_length=20, verbose_name='销售编号')),
                ('user_account', models.CharField(max_length=100, verbose_name='用户账号')),
                ('phone_number', models.CharField(max_length=20, verbose_name='手机号码')),
                ('after_sales_type', models.CharField(max_length=100, verbose_name='申请售后类型')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('initiation_time', models.DateTimeField(verbose_name='发起售后时间')),
                ('status', models.CharField(max_length=100, verbose_name='售后状态')),
            ],
            options={
                'verbose_name': '售后信息表',
                'verbose_name_plural': '售后信息表',
            },
        ),
        migrations.CreateModel(
            name='Broadcaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_code', models.CharField(max_length=20, verbose_name='主播编号')),
                ('broadcaster_name', models.CharField(max_length=100, verbose_name='主播姓名')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('signed_platform', models.CharField(max_length=50, verbose_name='签约平台')),
                ('operating_company', models.CharField(max_length=100, verbose_name='运营公司')),
                ('personal_homepage', models.URLField(verbose_name='个人主页')),
                ('expertise', models.CharField(max_length=100, verbose_name='特长')),
            ],
            options={
                'verbose_name': '主播信息表',
                'verbose_name_plural': '主播信息表',
            },
        ),
        migrations.CreateModel(
            name='BroadcastPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_code', models.CharField(max_length=20, verbose_name='主播编号')),
                ('monthly_broadcasts', models.IntegerField(verbose_name='本月直播')),
                ('monthly_featured_products', models.IntegerField(verbose_name='本月推荐商品')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售额')),
                ('tips_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='打赏收入')),
                ('standard_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='标准工资')),
                ('reward_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='奖励权重')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '主播绩效表',
                'verbose_name_plural': '主播绩效表',
            },
        ),
        migrations.CreateModel(
            name='LiveBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_code', models.CharField(max_length=20, verbose_name='主播编号')),
                ('broadcast_code', models.CharField(max_length=20, verbose_name='直播编号')),
                ('broadcast_time', models.DateTimeField(verbose_name='直播时间')),
                ('working_minutes', models.IntegerField(verbose_name='工作时长（分钟）')),
                ('product_code', models.CharField(max_length=20, verbose_name='带货商品编号')),
                ('product_order', models.IntegerField(verbose_name='带货顺序')),
            ],
            options={
                'verbose_name': '主播排期表',
                'verbose_name_plural': '主播排期表',
            },
        ),
        migrations.CreateModel(
            name='LiveBroadcastInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_code', models.CharField(max_length=20, verbose_name='直播编号')),
                ('broadcast_name', models.CharField(max_length=100, verbose_name='直播名称')),
                ('live_viewers', models.IntegerField(verbose_name='实时人数')),
                ('average_fan_duration', models.IntegerField(verbose_name='粉丝平均停留时间（分钟）')),
                ('click_count', models.IntegerField(verbose_name='功能点击数')),
                ('tips_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='打赏金额')),
                ('interaction_count', models.IntegerField(verbose_name='互动数')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='实时记录时间')),
            ],
            options={
                'verbose_name': '直播信息表',
                'verbose_name_plural': '直播信息表',
            },
        ),
        migrations.CreateModel(
            name='LiveBroadcastPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_code', models.CharField(max_length=20, verbose_name='直播编号')),
                ('broadcast_name', models.CharField(max_length=100, verbose_name='直播名称')),
                ('broadcast_platform', models.CharField(max_length=50, verbose_name='直播平台')),
                ('broadcast_link', models.URLField(verbose_name='直播链接')),
                ('broadcast_description', models.TextField(verbose_name='直播简介')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '直播计划表',
                'verbose_name_plural': '直播计划表',
            },
        ),
        migrations.CreateModel(
            name='OperatingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, verbose_name='运营账号编号')),
                ('platform', models.CharField(max_length=50, verbose_name='账号平台')),
                ('account_homepage', models.URLField(verbose_name='账号主页')),
                ('fan_count', models.IntegerField(verbose_name='粉丝数')),
                ('establishment_date', models.DateField(verbose_name='建立日期')),
                ('operator_number', models.CharField(max_length=50, verbose_name='运营主播编号')),
                ('account_content', models.CharField(max_length=50, verbose_name='账号内容')),
                ('total_videos', models.IntegerField(verbose_name='总视频数')),
                ('total_views', models.BigIntegerField(verbose_name='总播放量')),
            ],
            options={
                'verbose_name': '运营账号表',
                'verbose_name_plural': '运营账号表',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, verbose_name='商品编号')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('monthly_sales', models.IntegerField(verbose_name='本月销量')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本月销售额')),
                ('monthly_live_count', models.IntegerField(verbose_name='月参与直播数')),
                ('gross_profit_margin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='毛利率')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='商品记录时间')),
            ],
            options={
                'verbose_name': '商品信息表',
                'verbose_name_plural': '商品信息表',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, verbose_name='采购订单编号')),
                ('product_code', models.CharField(max_length=20, verbose_name='商品编号')),
                ('supplier_code', models.CharField(max_length=20, verbose_name='来源供应商编号')),
                ('quantity', models.IntegerField(verbose_name='采购数量')),
                ('purchaser', models.CharField(max_length=100, verbose_name='采购员')),
                ('warehouse', models.CharField(max_length=100, verbose_name='入库仓库')),
                ('purchase_time', models.DateTimeField(verbose_name='采购时间')),
                ('arrival_time', models.DateTimeField(verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '采购信息表',
                'verbose_name_plural': '采购信息表',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(max_length=20, verbose_name='销售编号')),
                ('broadcast_code', models.CharField(max_length=20, verbose_name='所属直播编号')),
                ('product_code', models.CharField(max_length=20, verbose_name='商品编号')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易总价')),
                ('order_info', models.CharField(max_length=200, verbose_name='销售订单信息')),
                ('order_time', models.DateTimeField(verbose_name='下单时间')),
            ],
            options={
                'verbose_name': '销售信息表',
                'verbose_name_plural': '销售信息表',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, verbose_name='商品编号')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('specification', models.CharField(max_length=50, verbose_name='规格')),
                ('warehouse_code', models.CharField(max_length=20, verbose_name='仓库编码')),
                ('stock_quantity', models.IntegerField(verbose_name='库存数量')),
                ('warehouse_manager', models.CharField(max_length=50, verbose_name='仓库管理员')),
            ],
            options={
                'verbose_name': '库存信息表',
                'verbose_name_plural': '库存信息表',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=20, verbose_name='供应商编号')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('product_code', models.CharField(max_length=20, verbose_name='商品编号')),
                ('supply_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='供应价格')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('total_purchases', models.IntegerField(verbose_name='累计采购')),
            ],
            options={
                'verbose_name': '供应商信息表',
                'verbose_name_plural': '供应商信息表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='昵称')),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=264)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男'), ('2', '未知')], default='2', max_length=1)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('role', models.CharField(choices=[('1', '工作人员'), ('2', '主播')], default='3', max_length=1, verbose_name='角色')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '平台用户',
                'verbose_name_plural': '平台用户',
                'db_table': 'platform_user',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
    ]
